version: "3.2"

services:
  app:
    image: pathtolife/pathtolife-typing
    restart: always
    environment:
      - VIRTUAL_HOST=${HOST_DOMAIN}
      - LETSENCRYPT_HOST=${HOST_DOMAIN}
      - LETSENCRYPT_EMAIL=${HOST_EMAIL}
    networks:
      - proxy-tier
  proxy:
    image: jwilder/nginx-proxy
    restart: always
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: 'true'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./letsencrypt-certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - app
    networks:
      - proxy-tier
  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - ./letsencrypt-acme:/etc/acme.sh
      - ./letsencrypt-certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - proxy
    networks:
      - proxy-tier

networks:
  proxy-tier:
